export interface Country {
    name: string;
    code: string;
}
  
export const countries: Country[] = [
  { name: 'Afganisztán', code: 'AF' },
  { name: 'Albánia', code: 'AL' },
  { name: 'Algéria', code: 'DZ' },
  { name: 'Amerikai Szamoa', code: 'AS' },
  { name: 'Andorra', code: 'AD' },
  { name: 'Angola', code: 'AO' },
  { name: 'Antigua és Barbuda', code: 'AG' },
  { name: 'Argentína', code: 'AR' },
  { name: 'Amerikai Egyesült Államok', code: 'US' },
  { name: 'Azerbajdzsán', code: 'AZ' },
  { name: 'Bahama-szigetek', code: 'BS' },
  { name: 'Bahrein', code: 'BH' },
  { name: 'Banglades', code: 'BD' },
  { name: 'Barbados', code: 'BB' },
  { name: 'Belize', code: 'BZ' },
  { name: 'Bénin', code: 'BJ' },
  { name: 'Bhután', code: 'BT' },
  { name: 'Bolívia', code: 'BO' },
  { name: 'Bosznia-Hercegovina', code: 'BA' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Brazília', code: 'BR' },
  { name: 'Brunei', code: 'BN' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Bulgária', code: 'BG' },
  { name: 'Burjátia (Oroszország része)', code: 'RU' },
  { name: 'Belgium', code: 'BE' },
  { name: 'Csehország', code: 'CZ' },
  { name: 'Chile', code: 'CL' },
  { name: 'Ecuador', code: 'EC' },
  { name: 'Kolumbia', code: 'CO' },
  { name: 'Kuba', code: 'CU' },
  { name: 'Kazahsztán', code: 'KZ' },
  { name: 'Kamerun', code: 'CM' },
  { name: 'Kanada', code: 'CA' },
  { name: 'Katar', code: 'QA' },
  { name: 'Kongói Köztársaság', code: 'CG' },
  { name: 'Kambodzsa', code: 'KH' },
  { name: 'Kína', code: 'CN' },
  { name: 'Koszovó', code: 'XK' },
  { name: 'Kuvait', code: 'KW' },
  { name: 'Kirgizisztán', code: 'KG' },
  { name: 'Libéria', code: 'LR' },
  { name: 'Líbia', code: 'LY' },
  { name: 'Lesotho', code: 'LS' },
  { name: 'Lettország', code: 'LV' },
  { name: 'Litvánia', code: 'LT' },
  { name: 'Luxemburg', code: 'LU' },
  { name: 'Malawi', code: 'MW' },
  { name: 'Malajzia', code: 'MY' },
  { name: 'Málta', code: 'MT' },
  { name: 'Marokkó', code: 'MA' },
  { name: 'Mauritánia', code: 'MR' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Mexikó', code: 'MX' },
  { name: 'Mikronézia', code: 'FM' },
  { name: 'Moldova', code: 'MD' },
  { name: 'Monaco', code: 'MC' },
  { name: 'Mongólia', code: 'MN' },
  { name: 'Mozambik', code: 'MZ' },
  { name: 'Namíbia', code: 'NA' },
  { name: 'Nauru', code: 'NR' },
  { name: 'Nepál', code: 'NP' },
  { name: 'Nicaragua', code: 'NI' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigéria', code: 'NG' },
  { name: 'Norvégia', code: 'NO' },
  { name: 'Nyugat-Szahara', code: 'EH' },
  { name: 'Németország', code: 'DE' },
  { name: 'Oroszország', code: 'RU' },
  { name: 'Ausztria', code: 'AT' },
];

